[versions]
agp = "8.3.2"
javax-inject = "1"
logging-interceptor = "4.11.0"
org-jetbrains-kotlin-android = "1.9.0"
core-ktx = "1.13.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.8.2"
activity-compose = "1.9.0"
compose-bom = "2024.06.00"
retrofit = "2.9.0"
org-jetbrains-kotlin-jvm = "1.9.0"
appcompat = "1.7.0"
material = "1.12.0"
hilt = "2.48.1"
orbit = "6.1.0"
coil = "2.3.0"
paging = "3.3.0"
coroutines-core = "1.8.0"
room = "2.6.1"
annotation = "1.8.0"
ktlint = "11.3.2"
androidx-credentials = "1.2.2"
androidx-credentials-play-services-auth = "1.2.2"
googleid = "1.1.0"

[libraries]
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle-runtime-ktx"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.7"}
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidx-credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidx-credentials-play-services-auth" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }


datastore = { module = "androidx.datastore:datastore-preferences", version = "1.1.1" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version = "1.0.0"}
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.12.0"}
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.5.0"}
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt" , name = "hilt-navigation-compose", version = "1.2.0"}
orbit-core = { group = "org.orbit-mvi", name = "orbit-core", version.ref = "orbit"}
orbit-viewmodel = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "orbit"}
orbit-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "orbit"}
splash = { group = "androidx.core", name = "core-splashscreen", version = "1.0.1" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil"}
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil"}
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging"}
paging-common = {group = "androidx.paging", name = "paging-common", version.ref = "paging"}
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging"}

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref="coroutines-core"}

room-runtime = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room"}
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin-android"}
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "org-jetbrains-kotlin-android"}
com-android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }





